# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 626db66a8d796780b9fb6eb5bccf6394846450571fc587eec96a20832f83677fc593765abc4a07e7a694276e3782d5daaafe5d7369e71efd39d777fe38f3e2ae

test:
  secret_key_base: f735a86035d171da3f948df9d90fd6375ea6dfaba7e99cf8a03cc2ff99efbd78399728840739763fb033c8e3402a79513f39ec978faeaf2bc5384d4868d4185c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
